// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jxqeoenhiqdtzzqbjwqz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp4cWVvZW5oaXFkdHp6cWJqd3F6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzUzNTM4MTEsImV4cCI6MjA1MDkyOTgxMX0.NWxBQQynZTiB6WEz3nMMLWH3jfqMjS5BHRyma09PZVM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);